### ISSUE TITLE
'Prodigy' object has no attribute '_step_count' error

### ISSUE THREAD

**Issue by jabacrack** [derrian-distro/LoRA_Easy_Training_Scripts#291]
I tried run lora training with prodigy optimizer and cosine scheduler and get next error:
```
Traceback (most recent call last):
  File "E:\LoRA_Easy_Training_Scripts\backend\sd_scripts\sdxl_train_network.py", line 228, in <module>
    trainer.train(args)
  File "E:\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 1258, in train
    optimizer.step()
  File "e:\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\accelerate\optimizer.py", line 170, in step
    self.optimizer.step(closure)
  File "e:\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\LoraEasyCustomOptimizer\CosineAnnealingWarmRestarts.py", line 49, in wrapper
    instance._step_count += 1
AttributeError: 'Prodigy' object has no attribute '_step_count'
```
My full config
```
[[subsets]]
caption_extension = ".txt"
image_dir = "E:/lora/datasets"
name = "test"
num_repeats = 3

[train_mode]
train_mode = "lora"

[general_args.args]
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
mixed_precision = "bf16"
gradient_checkpointing = true
seed = 1337
max_token_length = 225
prior_loss_weight = 1.0
xformers = true
max_train_steps = 2500
cache_latents = true
cache_latents_to_disk = true
sdxl = true
pretrained_model_name_or_path = "E:/Models/Stable-diffusion/illustriousXL_v01.safetensors"

[general_args.dataset_args]
resolution = [ 1024, 1024,]
batch_size = 2

[network_args.args]
network_dim = 16
network_alpha = 16.0
min_timestep = 0
max_timestep = 1000

[optimizer_args.args]
lr_scheduler = "cosine"
optimizer_type = "Prodigy"
lr_scheduler_type = "LoraEasyCustomOptimizer.CosineAnnealingWarmRestarts.CosineAnnealingWarmRestarts"
lr_scheduler_num_cycles = 1
loss_type = "l2"
learning_rate = 1.0
warmup_ratio = 0.03
unet_lr = 1.0
text_encoder_lr = 0.25
max_grad_norm = 1.0
min_snr_gamma = 5

[saving_args.args]
save_precision = "bf16"
save_model_as = "safetensors"
tag_occurrence = true
save_every_n_epochs = 1
save_toml = true
output_dir = "E:/lora/result"
output_name = "lolihmv"
tag_file_location = "E:/lora/train"
save_toml_location = "E:/lora/train"

[noise_args.args]
multires_noise_iterations = 8
multires_noise_discount = 0.4

[bucket_args.dataset_args]
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64

[network_args.args.network_args]
conv_dim = 16
conv_alpha = 16.0
algo = "ia3"

[optimizer_args.args.lr_scheduler_args]
min_lr = 0.1
gamma = 0.9

[optimizer_args.args.optimizer_args]
weight_decay = "0.01"
betas = "0.9,0.99"
decouple = "True"
d_coef = "1.0"

```

**Comment by derrian-distro** [comment]
I'm pretty sure this is a case of Prodigy, in all it's odd glory, being odd, like usual. I believe the expected use case for prodigy is to use it with Constant, as it edits the LR itself during runtime, and other schedulers that follow an actual schedule interfere with the optimizer's intended use case. I can look into it, but it's likely not something I can change as this is within the realm of prodigy being unusual, and not the CAWR scheduler being unusual

**Comment by Seedmanc** [comment]
Same here with CAME. I've successfully used it with CAWR before the update, so it's not the optimizer's fault, it's not even adaptive (I think).

**Comment by WakeUpLibra** [comment]
I had the same issue with pretty much the same config. It always appeared when using CosineAnnealingWarmRestarts scheduler, regardless of the optimizer. I fixed it as follows:
edited CosineAnnealingWarmRestarts in LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages\LoraEasyCustomOptimizer

```
def __init__(
    self,
    optimizer: Optimizer,
    gamma: float,
    cycle_multiplier: float = 1,
    first_cycle_max_steps: int = 1,
    min_lr: float = 1e-6,
    warmup_steps: int = 0,
    last_epoch: int = -1,
) -> None:
    if not isinstance(optimizer, Optimizer):
        raise TypeError(f"{type(optimizer).__name__} is not an Optimizer")
#ADDED THIS
    if not hasattr(optimizer, "_step_count"):
        optimizer._step_count = 0  
#ADDED THIS
    self.optimizer = optimizer
    self.cycle_multiplier = cycle_multiplier
    self.gamma = gamma
    self.last_epoch = last_epoch
```
And script worked, Lora was trained successfully (more or less).
I'm not sure if this is the right solution, works well and doesn't break something else, but maybe this will help somehow in error fixing.

**Comment by derrian-distro** [comment]
yes, that should fix it, I looked into it, but didn't have the time to actually fix it yet, but I did notice the difference between my CAWR and RAWR schedulers, I'll put out a fix for it when I have the chance. The problem was that torch changed how it's optimizer worked in newer versions, and since I personally don't use CAWR anymore, I failed to notice

**Comment by derrian-distro** [comment]
The issue should be fixed in the newest dev update, sorry about the major delay, life got in the way

**Comment by AdAstra-93** [comment]
I'm still getting the same error, no matter which optimizer I choose

**Comment by Jelosus2** [comment]
Which error specifically

**Comment by AdAstra-93** [comment]
AttributeError: 'Prodigy' object has no attribute '_step_count'; it happened with every optimizer. For some reason now it's working as intended, but the error jumped on a fresh, new install just for you to know

EDIT: I've been testing more and seems like Prodigy optimizer with a CosineAnnealingLR scheduler, or specially CosineAnnealingLR with anything throws the error @Jelosus2 @derrian-distro

**Comment by derrian-distro** [comment]
I never got around to pushing the fix to main, I'll be trying to find some time this week to update torch to 2.7.1 and push my changes to main, but the issue is fixed on dev

**Comment by AdAstra-93** [comment]
hi @derrian-distro hope you're doing well, just curious if this fix was ever pushed to main

**Comment by Jelosus2** [comment]
It should have been fixed yes
